import React from 'react';
import Navbar from './components/Navbar';
import './App.css';
import Home from './components/pages/Home';
import { BrowserRouter as Router, Switch, Route } from 'react-router-dom';


import Acao from './components/pages/Acao';
import Acao2 from './components/pages/Acao2';
import Aeradogelo2 from './components/pages/Aeradogelo2';
import Aestrada47 from './components/pages/Aestrada47';
import Afacedua from './components/pages/Afacedua';
import Afamilia from './components/pages/Afamilia';
import Afazenda from './components/pages/Afazenda';
import Afazenda2 from './components/pages/Afazenda2';
import Afazenda3 from './components/pages/Afazenda3';
import Afazenda4 from './components/pages/Afazzenda4';
import Agenteo from './components/pages/Agenteo';
import Albertnobbs from './components/pages/Albertnobbs';
import Alegiao from './components/pages/Alegiao';
import Altitude from './components/pages/Altitude';
import Amenteqm from './components/pages/Amenteqm';
import Amityvilleot from './components/pages/Amityvilleot';
import Amordoentio from './components/pages/Amordoentio';
import Amorzumbi from './components/pages/Amorzumbi';
import Animacao from './components/pages/Animacao';
import Anjosdanoite from './components/pages/Anjosdanoite';
import Aocasiaofl from './components/pages2/Aocasiaofl';
import Aparelhagens from "./components/pages/Aparelhagens";
import Apostolopauc from './components/pages/Apostolopauc';
import Apresa from './components/pages2/Apresa';
import Aprincesa from './components/pages/Aprincesa';
import Arecompensa from './components/pages2/Arecompensa';
import Arquiteturadd from './components/pages/Arquiteturadd';
import Aslegioese from './components/pages/Aslegioese';
import Assasinoapf from './components/pages/Assasinoapf';
import Ateofinal from './components/pages/Ateofinal';
import Atravessia from './components/pages/Atravessia';
import Atualidade from './components/pages/Atualidade';
import Aturmadam24 from './components/pages/Aturmadam24';
import Aturmadamonica from './components/pages/Aturmadamonica';
import Aventura from './components/pages/Aventura';
import Avitimaperfeita from './components/pages/Avitimaperfeita';
import Bandnews from './components/pages/Bandnews';
import Bandnews2 from './components/pages/Bandnews2';
import Bandsp from './components/pages/Bandsp';
import Batman from './components/pages/Batman';
import Beladonna from './components/pages/Beladonna';
import Bloodrayne3 from './components/pages/Bloodrayne3';
import Boasnovas from './components/pages/Boasnovas';
import Bravestorm from './components/pages/BraveStorm';
import Buffyacv from './components/pages/Buffyacv';
import Cadeoh from './components/pages/Cadeoh';
import Calculoiv from './components/pages2/Calculoiv';
import Camggw from './components/pages2/Camggw';
import Canaisp from './components/pages/Canaisp';
import Canaisrun from './components/pages/Canaisrun';
import Cartasdua from './components/pages2/Cartasdua';
import Cascao from './components/pages/Cascao';
import Cebolinha from './components/pages/Cebolinha';
import Cincodg from './components/pages/Cincodg';
import Cindiel from './components/pages/Cindiel';
import Cnnbr from './components/pages/Cnnbr';
import Comedia from './components/pages/Comedia';
import Comedia2 from './components/pages/Comedia2';
import Comedyc from './components/pages/Comedyc';
import Comedyc2 from './components/pages/Comedyc2';
import Commebol1 from './components/pages/Commebol1';
import Conmebol2 from './components/pages/Conmebol2';
import Conmebol3 from './components/pages/Conmebol3';
import Criatura from './components/pages/Criatura';
import Crime from './components/pages/Crime';
import Daaz from './components/pages/Daaz';
import Daaz10 from './components/pages/Daaz10';
import Daaz11 from './components/pages2/Daaz11';
import Daaz12 from './components/pages2/Daaz12';
import Daaz2 from './components/pages/Daaz2';
import Daaz3 from './components/pages/Daaz3';
import Daaz4 from './components/pages/Daaz4';
import Daaz5 from './components/pages/Daaz5';
import Daaz6 from './components/pages/Daaz6';
import Daaz7 from './components/pages/Daaz7';
import Daaz8 from './components/pages/Daaz8';
import Daaz9 from './components/pages/Daaz9';
import Dazn from './components/pages/Dazn';
import Deencontrosam from './components/pages/Deencontrosam';
import Details from './components/pages/det';
import Details2 from './components/pages/Detail2';
import Detencao from './components/pages2/Detencao';
import Diario from './components/pages/Diario';
import Disneyc from './components/pages/Disneyc';
import Documentarios from './components/pages/Documentarios';
import Drama from './components/pages/Drama';
import Drama2 from './components/pages/Drama2';
import Drama3 from './components/pages2/Drama3';
import Elvis from './components/pages/Elvis';
import Embuscadaliberdade from './components/pages/Embuscadaliberdade';
import Emnomedopai from './components/pages/Emnomedopai';
import Entreoamoreafama from './components/pages/Entreoamoreafama';
import Espn from './components/pages/Espn';
import Espn2 from './components/pages/Espn2';
import Espn3 from './components/pages/Espn3';
import Euronews from './components/pages/Euronews';
import Familiasop from './components/pages/Familiasop';
import Fantasia from './components/pages/Fantasia';
import Ficcao from './components/pages/Ficcao';
import Filmesn from './components/pages/Filmesn';
import Fmodia from './components/pages/Fmodia';
import Foradecontrole from './components/pages2/Foradecontrole';
import Friends from './components/pages/Friends';
import Fungindodopassado from './components/pages/Fugindodopassado';
import Gameoft from './components/pages/Gameoft';
import Gameoftr from './components/pages/Gameoftr';
import Gamert1e1 from './components/pages/Gamert1e1';
import Gamert1e2 from './components/pages/Gamert1e2';
import Gamert1e3 from './components/pages/Gamert1e3';
import Gamert1e4 from './components/pages/Gamert1e4';
import Gamert1e5 from './components/pages/Gamert1e5';
import Globom from './components/pages/Globom';
import Globonews from './components/pages/Globonews';
import Globonews2 from './components/pages/Globonews2';
import Globosp from './components/pages/Globosp';
import Gossebump2 from './components/pages/Gossebump2';
import Graopara from './components/pages/Graopara';
import Hbof from './components/pages/Hbof';
import Hellraiser from './components/pages2/Hellraiser';
import Homemasa from './components/pages/Homemasa';
import Homensemfuria from './components/pages2/Homensemfuria';
import Itvtv from './components/pages/Itvtv';
import Jogadadm from './components/pages/Jogadadm';
import Jogosv from './components/pages/Jogosv';
import Jogosve1 from './components/pages/Jogosve1';
import Jogosvec from './components/pages/Jogosvec';
import Jogosvef from './components/pages/Jogosvef';
import Jornalismo from './components/pages/Jornalismo';
import Kenanek from './components/pages/Kenanek';
import Kpoptv from './components/pages/Kpoptv';
import Kronehit from './components/pages/Kronehit';
import Kv1 from './components/pages/Kv1';
import Lama from './components/pages/Lama';
import Liberdadefm from './components/pages/Liberdadefm';
import Lilaee from './components/pages2/Lilaee';
import Linewalker2 from './components/pages/Linewalker2';
import Luanegra from './components/pages2/Luanegra';
import Magali from './components/pages/Magali';
import Mamonasps from './components/pages/Mamonasps';
import Marighela from './components/pages2/Marighela';
import Megapix from './components/pages/Megapix';
import Milena from './components/pages/Milena';
import Momentum from './components/pages/Momentum';
import Monica from './components/pages/Monica';
import Musicas from './components/pages/Musicas';
import Nezhacpv from './components/pages/Nezhacpv';
import Nocaute from './components/pages/Nocaute';
import Notodopoder from './components/pages/Notopodopoder';
import Novelas from './components/pages/Novelas';
import Noventaenove from './components/pages/Noventaenove';
import Oagentemirim from './components/pages/Oagentemirim';
import Obsessao from './components/pages/Obsessao';
import Ocaminho from './components/pages/Ocaminho';
import Ocaminhodn from './components/pages/Ocaminhosn';
import Odespertar from './components/pages/Odespertar';
import Olivroderute from './components/pages/Olivroderute';
import Omongeapdb from './components/pages/Omongeapdb';
import Operacoese from './components/pages/Operacoese';
import Oprecodg from './components/pages/Oprecodg';
import Opredadora from './components/pages/Opredadora';
import Oreidamontanha from './components/pages/Oreidamontanha';
import Oresgateduv from './components/pages/Oresgateduv';
import Osalvador from './components/pages/Osalvador';
import Osdeusesdel2 from './components/pages/Os deusesdel2';
import Osdezmandamentos from './components/pages/Osdezmandamentos';
import Osdozec from './components/pages/Osdozec';
import Osdozemacacos from './components/pages/Osdozemacacos';
import Osegredo from './components/pages2/Osegredo';
import Osquatro1 from './components/pages/Osquatro1';
import Ossimpson from './components/pages2/Ossimpson';
import Otrapaceiro from './components/pages/Otrapaceiro';
import Pagandobqmt from './components/pages/Pagandobqmt';
import Parttk from './components/pages/Parttk';
import Passagempav from './components/pages/Passagempav';
import Perfeicao from './components/pages/Perfeicao';
import Playcda from './components/pages/Playcda';
import Playclass from './components/pages/Playclass';
import Playlistyou from './components/pages/Playlistyou';
import Playnetmovie from './components/pages/Playnetmovie';
import Plutoacao from './components/pages2/Plutoacao';
import Plutoaf from './components/pages2/Plutoaf';
import Plutocom from './components/pages2/Plutocom';
import Plutocomr from './components/pages2/Pluotcomr';
import Plutodrama from './components/pages2/Plutodrama';
import Plutofc from './components/pages2/Plutofc';
import Plutonac from './components/pages2/Plutonac';
import Plutoromance from './components/pages2/Plutoromance';
import Plutoser from './components/pages/Plutoser';
import Plutosucesso from './components/pages2/Plutosucesso';
import Plutotdam from './components/pages/Plutotdam';
import Poderel from './components/pages/Poderel';
import Pokemon from './components/pages/Pokemon';
import Porquees from './components/pages/Porquees';
import Powerr from './components/pages/Powerr';
import Premier from './components/pages/Premier';
import Premiere2 from './components/pages/Premiere2';
import Premiere3 from './components/pages/Premiere3';
import Presane from './components/pages2/Presane';
import Radios from './components/pages/Radios';
import Rauland from './components/pages/Rauland';
import Rba from './components/pages/Rba';
import Rboasnovas from './components/pages/Rboasnovas';
import Re1sident from './components/pages/Re1sident';
import Recordnews from './components/pages/Recordnews';
import Recordrj from './components/pages/Recordrj';
import Recordsc from './components/pages/Recordsc';
import Redencao from './components/pages/Redencao';
import Redetv from './components/pages/Redetv';
import Relacaoexplosiva from './components/pages/Relacaoexplosiva';
import Rittv from './components/pages/Rittv';
import Romance from './components/pages/Romance';
import Ruepa from './components/pages/Ruepa';
import Runtimeacao from './components/pages/Runtimeacao';
import Runtimecom from './components/pages/Runtimecom';
import Runtimepri from './components/pages/Runtimepri';
import Ruslan from './components/pages/Ruslan';
import Samurayx2 from './components/pages/Samurayx2';
import Sanguenaveia from './components/pages/Sanguenaveia';
import Sbt from './components/pages/Sbt';
import Segredo from './components/pages/Segredo';
import Seriegot from './components/pages/Seriegot';
import Series from './components/pages/Series';
import Sonhosroubados from './components/pages/Sonhosroubados';
import Sosenhorda from './components/pages2/Sosenhorda';
import Sporttv from './components/pages/Sporttv';
import Sporttv2 from './components/pages/Sporttv2';
import Sporttv3 from './components/pages/Sporttv3';
import Stretfp from './components/pages/Stretfp';
import Sulamerica from './components/pages/Sulamerica';
import Superhli from './components/pages2/Superhli';
import Suspense from './components/pages/Suspense';
import Tempodc from './components/pages/Tempodc';
import Terror from './components/pages/Terror';
import Terror2 from './components/pages2/Terros2';
import Terrorns from './components/pages/Terrorns';
import Teste from './components/pages/Teste';
import Teste2 from './components/pages/Teste2';
import Teste3 from './components/pages/Teste3';
import Thewd from './components/pages/Thewd';
import Tnts1 from './components/pages/Tnts1';
import Tntsport2 from './components/pages/Tntsport2';
import Tntsport5 from './components/pages/Tntsports5';
import Tntsports7 from './components/pages/Tntsports7';
import Tntsports8 from './components/pages/Tntsports8';
import Topgun from './components/pages/Topgun';
import Tophits from './components/pages/Tophits';
import Topmixtv from './components/pages/Topmixtv';
import Toptv from './components/pages/Toptv';
import Tormenta from './components/pages/Tormenta';
import Tudoporjustica from './components/pages/Tudoporjusitca';
import Tvab from './components/pages/Tvab';
import Tvamulherb from './components/pages/Tvamulherb';
import TVs from './components/pages/TVs';
import Tvsf from './components/pages/Tvsf';
import TVsp from './components/pages/Tvsp';
import Twinpeaks from './components/pages/Twinpeaks';
import Umjovememapuros from './components/pages/Umjovememapuros';
import Ummaluconp from './components/pages2/Ummaluconp';
import Videoclips from './components/pages/Vdeoclips';
import Warnertv from './components/pages/Warnertv';
import Youtubeml from './components/pages/Youtubeml';
import Norastrodb from './components/pages2/Norastrodb';
import Desejodn from './components/pages2/Desejodn';
import Pecadosals from './components/pages2/Pecadosals';
import Oculpado from './components/pages2/Oculpado';
import Alexrct from './components/pages2/Alexrct';
import Oscacadores from './components/pages2/Oscacadores';
import Adesencantada from './components/pages2/Adesencantada';
import Cavaleirodalua from './components/pages2/Cavaleirodalua';
import Panteranwps from './components/pages2/Panteranwps';
import Esposada from './components/pages2/Esposada';
import Guardioesg from './components/pages2/Guardioesg';
import Omemedomal from './components/pages2/Omemedomal';
import Halo from './components/pages2/Halo';
import Homemcws from './components/pages2/Homemcws';
import Vikingsv from './components/pages2/Vikingsv';
import Daaz13 from './components/pages2/Daaz13';
import Supermel from './components/pages2/Supermel';
import Cobrakai from './components/pages2/Cobrakai';
import See from './components/pages2/See';
import Peakb from './components/pages2/Peakb';
import Falcaosu from './components/pages2/Falcaosu';
import Inventandoa from './components/pages2/Inventandoa';
import Valedes from './components/pages2/Valedes';
import Umtirams from './components/pages2/Umtirams';
import Gaviaoa from './components/pages2/Gaviaoa';
import Alendavm from './components/pages2/Alendavm';
import Aslinhastdd from './components/pages2/Aslinhastdd';
import Hawa from './components/pages2/Hawa';
import Stretch from './components/pages2/Stretch';
import Foradealcance from './components/pages2/Foradealcance';
import Nanatsu1 from './components/pages2/Nanatsu1';
import Avataroca from './components/pages2/Avataroca';
import Mucholocosn from './components/pages2/Mucholocosn';
import Daaz14 from './components/pages2/Daaz14';
import Umalindamulher from './components/pages2/Umalindamulher';
import Alistads from './components/pages2/Alistads';
import Expressomn from './components/pages2/Expressomn';
import Ficcao2 from './components/pages2/Ficcao2';
import Bilhetedefuga from './components/pages2/Bilhetedefuga';
import Bandnewfm from './components/pages2/Bandnewfm';
import Bmcnews from './components/pages2/Bmcnews';
import Musica from './components/pages2/Musica';
import Gracinha from './components/pages2/Gracinha';
import Opoderosoc from './components/pages2/Opoderosoc';
import Batmanct from './components/pages2/Batmanct';
import Peleo from './components/pages2/Peleo';
import Otremdamorte from './components/pages2/Otremdamorte';
import Flordelizqa from './components/pages2/Flordelizqa';
import Mundoestranho from './components/pages2/mundoestranho';
import OpoderosocII from './components/pages2/OpoderosocII';
import Umsonhodeliberdade from './components/pages2/Umsonhodeliberdade';
import Osenhordaaor from './components/pages2/Osenhordaaor';
import Aviagemdchi from './components/pages2/Aviagemdchi';
import Snowdenht from './components/pages2/Snowdenht';
import Wandinha from './components/pages2/Wandinha';
import Operacaom from './components/pages2/Operacaom';
import Dozehus from './components/pages2/Dozehus';
import Daaz15 from './components/pages2/Daaz15';
import Pearlh from './components/pages2/Pearlh';
import Diariojb from './components/pages2/Diariojb';
import Comedia3 from './components/pages2/Comedia3';
import Cruella from './components/pages2/Cruella';
import Comoeuera from './components/pages2/Comoeuera';
import Olobodw from './components/pages2/Olobodw';
import Parasita from './components/pages2/Parasita';
import Yourname from './components/pages2/Yourname';
import Aesperadum from './components/pages2/Aesperadum';
import Flordelisenm from './components/pages2/Flordelisenm';
import Pulpfiction from './components/pages2/Pulpfiction';
import Sporttv4 from './components/pages2/Sporttv4';
import Treshomensc from './components/pages2/treshomensc';
import Faroeste from './components/pages2/Faroeste';
import Osbonsc from './components/pages2/Osbonsc';
import Cinemap from './components/pages2/Cinemap';
import Avidaebela from './components/pages2/Avidaebela';
import Psicose from './components/pages2/Psicose';
import Clubedaluta from './components/pages2/Clubedaluta';
import Garotas2 from './components/pages2/Garotas2';
import Cidadededeus from './components/pages2/Cidadededeus';
import Forrestg from './components/pages2/Forrestg';
import Guerranasestrelas from './components/pages2/Guerranasestrelas';
import Maldosa from './components/pages2/Maldosas';
import Interestelar from './components/pages2/Interestelar';
import Arcane from './components/pages2/Arcane';
import Daaz16 from './components/pages2/Daaz16';
import Alitaac from './components/pages2/Alitaac';
import Osenhoraaa from './components/pages2/Osenhoraaa';
import Round6 from './components/pages2/Round6';
import Ogatodb2 from './components/pages2/Ogatodb2';
import Opianista from './components/pages2/Opianista';
import Osenhordadt from './components/pages2/Osenhordadt';
import Tumulodv from './components/pages2/Tumulodv';
import Ossetes from './components/pages2/Ossetes';
import Eraumavezna from './components/pages2/Eraumavezna';
import Umestranhonn from './components/pages2/Umestranhonn';
import Whiplash from './components/pages2/Whiplash';
import Aorigem from './components/pages2/Aorigem';
import Ocasteloanimado from './components/pages2/Ocasteloanimado';
import Matrix from './components/pages2/Matrix';
import Osilenciodi from './components/pages2/Osilenciodi';
import Drama4 from './components/pages2/Drama4';
import Oresgater from './components/pages2/Oresgater';
import Daaz17 from './components/pages2/Daaz17';
import Oaltodc from './components/pages2/Oaltodc';
import Sevenscc from './components/pages2/Sevenscc';
import Aoutraha from './components/pages2/Aoutraha';
import Oxterminadorf2jf from './components/pages2/Oexterminadorf2jf';
import Oprofissional from './components/pages2/Oprofissional';
import Vingadoresu from './components/pages2/Vingadoresu';
import Omilagredc7 from './components/pages2/Omilagredc7';
import Omenu from './components/pages2/Omenu';
import Boatekiss from './components/pages2/Boatekiss';
import Tudoetlmt from './components/pages2/Tudoetlmt';
import Homemaranhanav from './components/pages2/Homemaranhanav';
import Gladiador from './components/pages2/Gladiador';
import Oldboydv from './components/pages2/Oldboydv';
import Osinfiltrados from './components/pages2/Osinfiltrados';
import Devoltapf from './components/pages2/Devoltapf';
import Acriada from './components/pages2/Acriada';
import Teenwolf from './components/pages2/Teenwolf';
import Bastardosi from './components/pages2/Bastardosi';
import Ograndetruque from './components/pages2/Ograndetruque';
import Daaz18 from './components/pages2/Daaz18';
import Afelicidadensc from './components/pages2/Afelicidadensc';
import Ossuspeitos from './components/pages2/Ossuspeitos';
import Ojogodaimitacao from './components/pages2/Ojogodaimitacao';
import Crime2 from './components/pages2/Crime2';
import Oodioquevs from './components/pages2/Oodioquevs';
import Ailhadomedo from './components/pages2/Ailhadomedo';
import Thriller from './components/pages2/Thriller';
import Thriller2 from './components/pages2/Thriller2';
import Amnesia from './components/pages2/Amnesias';
import Dozeanosde from './components/pages2/Dozeanosde';
import Ateoultimoh from './components/pages2/Ateoultimoh';
import Casamentoa from './components/pages2/Casamentoa';
import Historiasc from './components/pages2/Historiasc';
import Vaeveja from './components/pages2/Vaveja';
import Coringa from './components/pages2/Coringa';
import Umcontratempo from './components/pages2/Umcontratempo';
import Meupai from './components/pages2/Meupai';
import Vozesinocentes from './components/pages2/Vozesinocentes';
import Sharper from './components/pages2/sharper';
import Intocaveis from './components/pages2/Intocaveis';
import Hawai50 from './components/pages2/Hawai50';
import Anonimo from './components/pages2/Anonimo';
import Ossuspeitos2 from './components/pages2/Ossuspeitos2';
import Daaz19 from './components/pages2/Daaz19';
import Acincopdv from './components/pages2/Acincopdv';
import Djangolivre from './components/pages2/Djangolivre';
import Indianajcd from './components/pages2/Indianajcd';
import Clouds from './components/pages2/Clouds';
import Parafaf from './components/pages2/Parafaf';
import Melancolia from './components/pages2/Melancolia';
import Princesamono from './components/pages2/Princesamono';
import Demsl from './components/pages2/Demsl';
import Avidaemua from './components/pages2/Avidaemua';
import Dancacl from './components/pages2/Dancacl';
import Greenbook from './components/pages2/Greenbook';
import Tresanuncios from './components/pages2/Tresanuncios';
import Extraordinario from './components/pages2/Extraordinario';
import Mommy from './components/pages2/Mommy';
import Ligajs from './components/pages2/Ligajs';
import Memoriasa from './components/pages2/Memoriasa';
import Glassonion from './components/pages2/Glassonion';
import Meuamigoe from './components/pages2/Meuamigoe';
import Acaca from './components/pages2/Acaca';
import Togo from './components/pages2/Togo';
import Bohemianr from './components/pages2/Bohemianr';
import Daaz20 from './components/pages2/Daaz20';
import Ouronegro from './components/pages2/Ouronegro';
import Emancipation from './components/pages2/Emancipation';
import Acrediteemmim from './components/pages2/Acrediteemmim';
import Rastrosdus from './components/pages2/Rastrosdus';
import Drama5 from './components/pages2/Drama5';
import Obarcoim from './components/pages2/Obarcoim';
import Mil917 from './components/pages2/Mil917';
import Killbill1 from './components/pages2/Killbill1';
import Dark from './components/pages2/Dark';
import Quebrandog from './components/pages2/Quebrandog';
import Grantorino from './components/pages2/Grantorino';
import Osegredoeso from './components/pages2/Osegredoeso';
import Alien8 from './components/pages2/Alien8';
import M3gan from './components/pages2/M3gan';
import Pamelaa from './components/pages2/Pamelaa';
import Nosbracosa from './components/pages2/Nosbracosa';
import Fogocontrafogo from './components/pages2/Fogocontrafogo';
import Ogarotodl from './components/pages3/Ogarotodl';
import Daaz21 from './components/pages3/Daaz21';
import Filhosdi from './components/pages3/Filhosdi';
import Jogostsf from './components/pages3/Jogostsf';
import Omotoristat from './components/pages3/Omotoristat';
import Ligadajzs from './components/pages3/Ligadajzs';
import A13emenda from './components/pages3/A13emenda';
import Airmandadedg from './components/pages3/Airmandadedg';
import Temposmodernos from './components/pages3/Temposmodernos';
import Oreileao from './components/pages3/Oreileao';
import Prendamesfc from './components/pages3/Prendamesfc';
import Joor from './components/pages3/Joor';
import Estanoitevdc from './components/pages3/Estanoitevdc';
import Durodeatuar from './components/Durodeatuar';
import Oestranguladordb from './components/pages3/Oestranguladordb';
import Farofagk from './components/pages3/Farofagk';
import Amulhergtc from './components/pages3/Amulhergtc';
import Thebeatlese from './components/pages3/Thebeatlese';
import Fantasmaecia from './components/pages3/Fantasmaecia';
import Reidoringue from './components/pages3/Reidoringue';
import Daaz22 from './components/pages3/Daaz22';
import Sayen from './components/pages3/Sayen';
import Opoderealei from './components/pages3/Opoderealei';
import Babilonia from './components/pages3/Babilonia';
import Palmer from './components/pages3/Palmer';
import Napalmadamao from './components/pages3/Napalmadamao';
import Homemfvq from './components/pages3/Homemfvq';
import Johnwvj from './components/pages3/Johnwvj';
import Johnwndm from './components/pages3/Johnwndm';
import Johnw3 from './components/pages3/Jonhw3';
import Alguemqcc from './components/pages3/Alguemqcc';
import Johnw4 from './components/pages2/Johnw4';
import Ateoriadt from './components/pages3/Ateoriadt';
import Bandnews3 from './components/pages/Bandnews3';
import Nasuacm from './components/pages/Nasuacm';
import Amorov from './components/pages/Amorov';
import Imperiodaluz from './components/pages/Imperiodaluz';
import Alertamx from './components/pages/Alertamx';
import Opiorvdm from './components/pages/Opiorvdm';
import Batemap from './components/pages/Batemap';
import Olobov from './components/pages/Olobov';
import Inviesto from './components/pages/Infiesto';
import Herois from './components/pages/Herois';
import Alienor from './components/pages/Alienor';
import Osenhorda from './components/pages/Osenhorda';
import Destemida from './components/pages/Destemida';
import Umhomemds from './components/pages/Umhomemds';
import Walle from './components/pages/Walle';
import Nadadnf from './components/pages/Nadadnf';
import Osbansheesi from './components/pages/Osbansheesi';
import Violete from './components/pages/Violete';
import Upaa from './components/pages/Upaa';
import Narvik from './components/pages/Narvik';
import Junge from './components/pages/Junge';
import Caesdeal from './components/pages/Caesdeal';
import Noitein from './components/pages/Noitein';
import Setemum from './components/pages/Setemum';
import Halo4 from './components/pages/Halo4';
import Oinfernodg from './components/pages/Oinfernodg';
import Regra34 from './components/pages/Regra34';
import Umanji from './components/pages/Umanji';
import Matildaom from './components/pages/Matildaom';
import Aluzdm from './components/pages/Aluzdm';
import Peterpw from './components/pages/Peterpw';
import Umanmr from './components/pages/Umanmr';
import Ataquedc from './components/pages/Ataquedc';





















function App() {
  return (
    <Router>
      <Navbar />
      <Switch>
        <Route path='/' exact component={Home} />
        <Route path='/100' component={Jogostsf} />
        <Route path='/101' component={Oprofissional} />
        <Route path='/101299' component={Jogosvec} />
        <Route path='/1022206' component={Esposada} />
        <Route path='/1024530' component={Omemedomal} />
        <Route path='/1026624' component={Mucholocosn} />
        <Route path='/1032412' component={Quebrandog} />
        <Route path='/10358' component={Pagandobqmt} />
        <Route path='/103663' component={Acaca} />
        <Route path='/105' component={Devoltapf} />
        <Route path='/10534' component={Tormenta} />
        <Route path='/1061671' component={Pamelaa} />
        <Route path='/1065796' component={Umanji} />
        <Route path='/106646' component={Olobodw} />
        <Route path='/10681' component={Walle} />
        <Route path='/1072567' component={Inviesto} />
        <Route path='/1074656' component={Amorov} />
        <Route path='/1077280' component={Durodeatuar} />
        <Route path='/1081313' component={Estanoitevdc} />
        <Route path='/109513' component={Relacaoexplosiva} />
        <Route path='/11001' component={Umtirams} />
        <Route path='/11216' component={Cinemap} />
        <Route path='/1124' component={Ograndetruque} />
        <Route path='/112205' component={Afamilia} />
        <Route path='/11324' component={Ailhadomedo} />
        <Route path='/11327' component={Expressomn} />
        <Route path='/13455' component={Herois} />
        <Route path='/114' component={Umalindamulher} />
        <Route path='/11423' component={Memoriasa} />
        <Route path='/11658' component={Airmandadedg} />
        <Route path='/11817' component={Omongeapdb} />
        <Route path='/118683' component={Operacoese} />
        <Route path='/11937' component={Osdeusesdel2} />
        <Route path='/120' component={Osenhoraaa} />
        <Route path='/120143' component={Osquatro1} />
        <Route path='/121' component={Osenhordadt} />
        <Route path='/122' component={Osenhordaaor} />
        <Route path='/12477' component={Tumulodv} />
        <Route path='/12685' component={Bloodrayne3} />
        <Route path='/127770' component={Apostolopauc} />
        <Route path='/128' component={Princesamono} />
        <Route path='/129' component={Aviagemdchi} />
        <Route path='/13' component={Forrestg} />
        <Route path='/131631' component={Jogosve1} />
        <Route path='/131634' component={Jogosvef} />
        <Route path='/13223' component={Grantorino} />
        <Route path='/13805' component={Superhli} />
        <Route path='/139567' component={Fogocontrafogo} />
        <Route path='/1399' component={Gameoftr} />
        <Route path='/1402' component={Thewd} />
        <Route path='/14160' component={Upaa} />
        <Route path='/1422' component={Osinfiltrados} />
        <Route path='/146233' component={Ossuspeitos2} />
        <Route path='/155' component={Batmanct} />
        <Route path='/157336' component={Interestelar} />        
        <Route path='/157485' component={Aturmadamonica} />
        <Route path='/1585' component={Afelicidadensc} />
        <Route path='/15941' component={Poderel} />
        <Route path='/16279' component={Amenteqm} />
        <Route path='/164457' component={Tudoporjustica} />
        <Route path='/1654' component={Osdozec} />
        <Route path='/16869' component={Bastardosi} />
        <Route path='/1830' component={Osenhorda} />
        <Route path='/184125' component={Homemcws} />
        <Route path='/1891' component={Guerranasestrelas} />
        <Route path='/192134' component={Arecompensa} />
        <Route path='/199591' component={Presane} />
        <Route path='/20435' component={Otremdamorte} />
        <Route path='/205596' component={Ojogodaimitacao} />
        <Route path='/20941' component={Vozesinocentes} />
        <Route path='/221731' component={Samurayx2} />
        <Route path='/22331' component={Osdezmandamentos} />
        <Route path='/227300' component={Stretch} />
        <Route path='/228968' component={Jogadadm} />
        <Route path='/231474' component={Oscacadores} />
        <Route path='/23514' component={Diariojb} />
        <Route path='/23520' component={Fungindodopassado} />
        <Route path='/236735' component={Pecadosals} />
        <Route path='/238' component={Opoderosoc} />
        <Route path='/24' component={Killbill1} />
        <Route path='/240' component={OpoderosocII} />
        <Route path='/244786' component={Whiplash} />
        <Route path='/245891' component={Johnwvj} />
        <Route path='/25237' component={Vaeveja} />
        <Route path='/253020' component={Aestrada47} />
        <Route path='/25376' component={Osegredoeso} />
        <Route path='/254024' component={Afacedua} />
        <Route path='/254302' component={Notodopoder} />
        <Route path='/256474' component={Sanguenaveia} />
        <Route path='/265177' component={Mommy} />
        <Route path='/266856' component={Ateoriadt} />
        <Route path='/27205' component={Aorigem} />
        <Route path='/274' component={Osilenciodi} />
        <Route path='/27582' component={Assasinoapf} />
        <Route path='/277' component={Anjosdanoite} />
        <Route path='/278' component={Umsonhodeliberdade} />
        <Route path='/280' component={Oxterminadorf2jf} />
        <Route path='/284289' component={Foradealcance} />
        <Route path='/290098' component={Acriada} />
        <Route path='/296096' component={Comoeuera} />
        <Route path='/299534' component={Vingadoresu} />
        <Route path='/302401' component={Snowdenht} />
        <Route path='/303021' component={Osalvador} />
        <Route path='/3082' component={Temposmodernos} />
        <Route path='/308695' component={Alegiao} />
        <Route path='/309581' component={Lilaee} />
        <Route path='/311' component={Eraumavezna} />
        <Route path='/315162' component={Ogatodb2} />
        <Route path='/329235' component={Marighela} />
        <Route path='/324786' component={Ateoultimoh} />
        <Route path='/324857' component={Homemaranhanav} />
        <Route path='/324552' component={Johnwndm} />
        <Route path='/332672' component={Obsessao} />
        <Route path='/33511' component={Ogarotodl} />
        <Route path='/337404' component={Cruella} />
        <Route path='/338958' component={Adesencantada} />
        <Route path='/346' component={Ossetes} />
        <Route path='/346684' component={Embuscadaliberdade} />
        <Route path='/346808' component={Momentum} />
        <Route path='/348' component={Alien8} />
        <Route path='/359940' component={Tresanuncios} />
        <Route path='/361743' component={Topgun} />
        <Route path='/372058' component={Yourname} />
        <Route path='/372412' component={Apresa} />
        <Route path='/38017' component={Cartasdua} />
        <Route path='/387' component={Obarcoim} />
        <Route path='/389' component={Dozehus} />
        <Route path='/391486' component={Atravessia} />
        <Route path='/39414' component={Tempodc} />
        <Route path='/39564' component={Luanegra} />
        <Route path='/391698' component={Thebeatlese} />
        <Route path='/399579' component={Alitaac} />
        <Route path='/40096' component={Oaltodc} />
        <Route path='/407806' component={A13emenda} />
        <Route path='/408670' component={Oagentemirim} />
        <Route path='/406997' component={Extraordinario} />
        <Route path='/410537' component={Amityvilleot} />
        <Route path='/413452' component={Oresgateduv} />
        <Route path='/411088' component={Umcontratempo} />
        <Route path='/414906' component={Batman} />
        <Route path='/415214' component={Operacaom} />
        <Route path='/420808' component={Peterpw} />
        <Route path='/422821' component={Oprecodg} />
        <Route path='/424' component={Alistads} />
        <Route path='/429' component={Treshomensc} />
        <Route path='/423' component={Opianista} />
        <Route path='/424694' component={Bohemianr} />
        <Route path='/43549' component={Detencao} />
        <Route path='/437068' component={Omotoristat} />
        <Route path='/44113' component={Homensemfuria} />
        <Route path='/443700' component={Altitude} />
        <Route path='/444090' component={Oreidamontanha} />
        <Route path='/44665' component={Olivroderute} />
        <Route path='/447362' component={Avidaemua} />
        <Route path='/45170' component={Sonhosroubados} />
        <Route path='/458156' component={Johnw3} />
        <Route path='/458220' component={Palmer} />
        <Route path='/459075' component={Bravestorm} />
        <Route path='/470044' component={Oodioquevs} />
        <Route path='/47089' component={Ocaminhodn} />
        <Route path='/475557' component={Coringa} />
        <Route path='/488623' component={Rastrosdus} />
        <Route path='/490132' component={Greenbook} />
        <Route path='/49046' component={Nadadnf} />
        <Route path='/4935' component={Ocasteloanimado} />
        <Route path='/495386' component={Entreoamoreafama} />
        <Route path='/496243' component={Parasita} />
        <Route path='/497' component={Aesperadum} />
        <Route path='/500' component={Caesdeal} />
        <Route path='/50014' component={Historiasc} />
        <Route path='/50348' component={Opoderealei} />
        <Route path='/504198' component={Terrorns} />
        <Route path='/505642' component={Panteranwps} />
        <Route path='/50601' component={Cincodg} />
        <Route path='/510' component={Umestranhonn} />
        <Route path='/515001' component={Joor} />
        <Route path='/522924' component={Meuamigoe} />
        <Route path='/527641' component={Acincopdv} />
        <Route path='/530915' component={Mil917} />
        <Route path='/53172' component={Aocasiaofl} />
        <Route path='/533514' component={Violete} />
        <Route path='/536554' component={M3gan} />
        <Route path='/539' component={Psicose} />
        <Route path='/545611' component={Tudoetlmt} />
        <Route path='/550' component={Clubedaluta} />
        <Route path='/550776' component={Acrediteemmim} />
        <Route path='/55101' component={Oculpado} />
        <Route path='/556018' component={Kv1} />
        <Route path='/56295' component={Halo4} />
        <Route path='/581' component={Dancacl} />
        <Route path='/58448' component={Nocaute} />
        <Route path='/589157' component={Linewalker2} />
        <Route path='/593643' component={Omenu} />
        <Route path='/598' component={Cidadededeus} />
        <Route path='/600354' component={Meupai} />
        <Route path='/600583' component={Ataquedc} />
        <Route path='/603' component={Matrix} />
        <Route path='/603692' component={Johnw4} />
        <Route path='/606856' component={Togo} />
        <Route path='/614934' component={Elvis} />
        <Route path='/615457' component={Anonimo} />
        <Route path='/615777' component={Babilonia} />
        <Route path='/618344' component={Ligajs} />
        <Route path='/619930' component={Narvik} />
        <Route path='/62215' component={Melancolia} />
        <Route path='/622585' component={Aslegioese} />
        <Route path='/629' component={Ossuspeitos} />
        <Route path='/63' component={Osdozemacacos} />
        <Route path='/630566' component={Clouds} />
        <Route path='/631842' component={Batemap} />
        <Route path='/635302' component={Demsl} />
        <Route path='/637' component={Avidaebela} />
        <Route path='/637920' component={Omilagredc7} />
        <Route path='/640' component={Prendamesfc} />
        <Route path='/640146' component={Homemfvq} />
        <Route path='/646389' component={Alertamx} />
        <Route path='/652722' component={Nosbracosa} />   
        <Route path='/66113' component={Avitimaperfeita} />
        <Route path='/661374' component={Glassonion} />
        <Route path='/668482' component={Matildaom} />
        <Route path='/674324' component={Osbansheesi} />
        <Route path='/676' component={Pearlh} />
        <Route path='/676547' component={Aluzdm} />
        <Route path='/679' component={Alienor} />
        <Route path='/680' component={Pulpfiction} />
        <Route path='/68202' component={Cadeoh} />
        <Route path='/68348' component={Arquiteturadd} />
        <Route path='/68718' component={Djangolivre} />
        <Route path='/687354' component={Stretfp} />
        <Route path='/696374' component={Oinfernodg} />
        <Route path='/70160' component={Jogosv} />
        <Route path='/703451' component={Nasuacm} />
        <Route path='/707214' component={Ateofinal} />
        <Route path='/71211' component={Beladonna} />
        <Route path='/715931' component={Emancipation} />
        <Route path='/717980' component={Sharper} />
        <Route path='/725201' component={Agenteo} />
        <Route path='/73' component={Aoutraha} />
        <Route path='/7304' component={Norastrodb} />
        <Route path='/7345' component={Ouronegro} />
        <Route path='/73873' component={Albertnobbs} />
        <Route path='/73963' component={Criatura} />
        <Route path='/739986' component={Destemida} />
        <Route path='/740441' component={Napalmadamao} />
        <Route path='/740555' component={Dark} />
        <Route path='/742408' component={Peleo} />
        <Route path='/74549' component={Osegredo} />
        <Route path='/747803' component={Bilhetedefuga} />
        <Route path='/751741' component={Umanmr} />
        <Route path='/758009' component={Casamentoa} />
        <Route path='/759175' component={Aprincesa} />
        <Route path='/76203' component={Dozeanosde} />
        <Route path='/76600' component={Avataroca} />
        <Route path='/766507' component={Opredadora} />
        <Route path='/769' component={Osbonsc} />
        <Route path='/77' component={Amnesia} />
        <Route path='/770428' component={Emnomedopai} />
        <Route path='/77067' component={Amorzumbi} />
        <Route path='/77338' component={Intocaveis} />
        <Route path='/774752' component={Guardioesg} />
        <Route path='/77877' component={Umhomemds} />
        <Route path='/77949' component={Odespertar} />
        <Route path='/781456' component={Nezhacpv} />
        <Route path='/785534' component={Filhosdi} />
        <Route path='/788752' component={Olobov} />
        <Route path='/791373' component={Ligadajzs} />
        <Route path='/792237' component={Camggw} />
        <Route path='/79465' component={Otrapaceiro} />
        <Route path='/80299' component={Passagempav} />
        <Route path='/80544' component={Desejodn} />
        <Route path='/807' component={Sevenscc} />
        <Route path='/814757' component={Imperiodaluz} />
        <Route path='/81488' component={Mamonasps} />
        <Route path='/843794' component={Junge} />
        <Route path='/85' component={Indianajcd} />
        <Route path='/850871' component={Sayen} />
        <Route path='/851644' component={Garotas2} />
        <Route path='/852096' component={Fantasmaecia} />
        <Route path='/857' component={Oresgater} />
        <Route path='/8587' component={Oreileao} />
        <Route path='/862491' component={Amulhergtc} />
        <Route path='/869112' component={Alguemqcc} />
        <Route path='/87516' component={Oldboydv} />
        <Route path='/875303' component={Amordoentio} />
        <Route path='/877269' component={Mundoestranho} />
        <Route path='/877703' component={Teenwolf} />
        <Route path='/881164' component={Oestranguladordb} />
        <Route path='/890541' component={Setemum} />
        <Route path='/890980' component={Aslinhastdd} />
        <Route path='/893656' component={Gracinha} />
        <Route path='/8944' component={Foradecontrole} />
        <Route path='/899112' component={Noitein} />
        <Route path='/9003' component={Hellraiser} />
        <Route path='/92321' component={Parafaf} />
        <Route path='/937278' component={Opiorvdm} />
        <Route path='/943822' component={Reidoringue} />
        <Route path='/950' component={Aeradogelo2} />
        <Route path='/954293' component={Farofagk} />
        <Route path='/961707' component={Hawa} />
        <Route path='/96933' component={Porquees} />
        <Route path='/98' component={Gladiador} />
        <Route path='/989937' component={Nanatsu1} />
        <Route path='/997265' component={Regra34} />
        <Route path='/9978' component={Alexrct} />
        <Route path='/acao' component={Acao} />
        <Route path='/acao2' component={Acao2} />
        <Route path='/afazenda' component={Afazenda} />
        <Route path='/afazenda2' component={Afazenda2} />
        <Route path='/afazenda3' component={Afazenda3} />
        <Route path='/afazenda4' component={Afazenda4} />
        <Route path='/alendavm' component={Alendavm} />
        <Route path='/animacao' component={Animacao} />
        <Route path='/aparelhagens' component={Aparelhagens} />
        <Route path='/arcane' component={Arcane} />
        <Route path='/atualidade' component={Atualidade} />
        <Route path='/aturmadam24' component={Aturmadam24} />
        <Route path='/aventura' component={Aventura} />
        <Route path='/bandnewfm' component={Bandnewfm} />
        <Route path='/bandnews' component={Bandnews} />
        <Route path='/bandnews2' component={Bandnews2} />
        <Route path='/bandnews3' component={Bandnews3} />
        <Route path='/bandsp' component={Bandsp} />
        <Route path='/bmcnews' component={Bmcnews} />
        <Route path='/boatekiss' component={Boatekiss} />
        <Route path='/boasnovas' component={Boasnovas} />
        <Route path='/buffyacv' component={Buffyacv} />
        <Route path='/calculoiv' component={Calculoiv} />
        <Route path='/canaisp' component={Canaisp} />
        <Route path='/canaisrun' component={Canaisrun} />
        <Route path='/cascao' component={Cascao} />
        <Route path='/cavaleirodalua' component={Cavaleirodalua} />
        <Route path='/cebolinha' component={Cebolinha} />
        <Route path='/cindiel' component={Cindiel} />
        <Route path='/cnnbr' component={Cnnbr} />
        <Route path='/cobrakai' component={Cobrakai} />
        <Route path='/comedia' component={Comedia} />
        <Route path='/comedia2' component={Comedia2} />
        <Route path='/comedia3' component={Comedia3} />
        <Route path='/comedyc' component={Comedyc} />
        <Route path='/comedyc2' component={Comedyc2} />
        <Route path='/commebol1' component={Commebol1} />
        <Route path='/conmebol2' component={Conmebol2} />
        <Route path='/conmebol3' component={Conmebol3} />
        <Route path='/crime' component={Crime} />
        <Route path='/crime2' component={Crime2} />
        <Route path='/daaz' component={Daaz} />
        <Route path='/daaz10' component={Daaz10} />
        <Route path='/daaz11' component={Daaz11} />
        <Route path='/daaz12' component={Daaz12} />
        <Route path='/daaz13' component={Daaz13} />
        <Route path='/daaz14' component={Daaz14} />
        <Route path='/daaz15' component={Daaz15} />
        <Route path='/daaz16' component={Daaz16} />
        <Route path='/daaz17' component={Daaz17} />
        <Route path='/daaz18' component={Daaz18} />
        <Route path='/daaz19' component={Daaz19} />
        <Route path='/daaz20' component={Daaz20} />
        <Route path='/daaz21' component={Daaz21} />
        <Route path='/daaz22' component={Daaz22} />
        <Route path='/daaz20' component={Daaz} />
        <Route path='/daaz2' component={Daaz2} />
        <Route path='/daaz3' component={Daaz3} />
        <Route path='/daaz4' component={Daaz4} />
        <Route path='/daaz5' component={Daaz5} />
        <Route path='/daaz6' component={Daaz6} />
        <Route path='/daaz7' component={Daaz7} />
        <Route path='/daaz8' component={Daaz8} />
        <Route path='/daaz9' component={Daaz9} />
        <Route path='/dazn' component={Dazn} />
        <Route path='/deencontrosam' component={Deencontrosam} />
        <Route path='/details/:id' component={Details} />
        <Route path='/details2/:id' component={Details2} />
        <Route path='/diario' component={Diario} />
        <Route path='/disneyc' component={Disneyc} />
        <Route path='/documentarios' component={Documentarios} />
        <Route path='/drama' component={Drama} />
        <Route path='/drama2' component={Drama2} />
        <Route path='/drama3' component={Drama3} />
        <Route path='/drama4' component={Drama4} />
        <Route path='/drama5' component={Drama5} />
        <Route path='/espn' component={Espn} />
        <Route path='/espn2' component={Espn2} />
        <Route path='/espn3' component={Espn3} />
        <Route path='/euronews' component={Euronews} />
        <Route path='/falcaosu' component={Falcaosu} />
        <Route path='/familiasop' component={Familiasop} />
        <Route path='/fantasia' component={Fantasia} />
        <Route path='/faroeste' component={Faroeste} />
        <Route path='/ficcao' component={Ficcao} />
        <Route path='/ficcao2' component={Ficcao2} />
        <Route path='/filmesn' component={Filmesn} />
        <Route path='/flordelisenm' component={Flordelisenm} />
        <Route path='/flordelizqa' component={Flordelizqa} />
        <Route path='/fmodia' component={Fmodia} />
        <Route path='/friends' component={Friends} />
        <Route path='/gameoft' component={Gameoft} />
        <Route path='/Gamert1e1' component={Gamert1e1} />
        <Route path='/Gamert1e2' component={Gamert1e2} />
        <Route path='/Gamert1e3' component={Gamert1e3} />
        <Route path='/Gamert1e4' component={Gamert1e4} />
        <Route path='/Gamert1e5' component={Gamert1e5} />
        <Route path='/gaviaoa' component={Gaviaoa} />
        <Route path='/globom' component={Globom} />
        <Route path='/globonews' component={Globonews} />
        <Route path='/globonews2' component={Globonews2} />
        <Route path='/globosp' component={Globosp} />
        <Route path='/gossebump2' component={Gossebump2} />
        <Route path='/graopara' component={Graopara} />
        <Route path='/halo' component={Halo} />
        <Route path='/hawai50' component={Hawai50} />
        <Route path='/Hbof' component={Hbof} />
        <Route path='/homemasa' component={Homemasa} />
        <Route path='/inventandoa' component={Inventandoa} />
        <Route path='/itvtv' component={Itvtv} />
        <Route path='/jornalismo' component={Jornalismo} />
        <Route path='/kenanek' component={Kenanek} />
        <Route path='/kpoptv' component={Kpoptv} />
        <Route path='/kronehit' component={Kronehit} />
        <Route path='/lama' component={Lama} />
        <Route path='/liberdadefm' component={Liberdadefm} />
        <Route path='/magali' component={Magali} />
        <Route path='/maldosa' component={Maldosa} />
        <Route path='/Megapix' component={Megapix} />
        <Route path='/milena' component={Milena} />
        <Route path='/monica' component={Monica} />
        <Route path='/musica' component={Musica} />
        <Route path='/musicas' component={Musicas} />
        <Route path='/novelas' component={Novelas} />
        <Route path='/noventaenove' component={Noventaenove} />
        <Route path='/ocaminho' component={Ocaminho} />
        <Route path='/ossimpson' component={Ossimpson} />
        <Route path='/parttk' component={Parttk} />
        <Route path='/peakb' component={Peakb} />
        <Route path='/perfeicao' component={Perfeicao} />
        <Route path='/playcda' component={Playcda} />
        <Route path='/playclass' component={Playclass} />
        <Route path='/playlistyou' component={Playlistyou} />
        <Route path='/playnetmovie' component={Playnetmovie} />
        <Route path='/plutoacao' component={Plutoacao} />
        <Route path='/plutoaf' component={Plutoaf} />
        <Route path='/plutocom' component={Plutocom} />
        <Route path='/plutocomr' component={Plutocomr} />
        <Route path='/plutodrama' component={Plutodrama} />
        <Route path='/plutofc' component={Plutofc} />
        <Route path='/plutonac' component={Plutonac} />
        <Route path='/plutoromance' component={Plutoromance} />
        <Route path='/plutoser' component={Plutoser} />
        <Route path='/plutosucesso' component={Plutosucesso} />
        <Route path='/plutotdam' component={Plutotdam} />
        <Route path='/pokemon' component={Pokemon} />
        <Route path='/powerr' component={Powerr} />
        <Route path='/premier' component={Premier} />
        <Route path='/premiere2' component={Premiere2} />
        <Route path='/premiere3' component={Premiere3} />
        <Route path='/radios' component={Radios} />
        <Route path='/rauland' component={Rauland} />
        <Route path='/rba' component={Rba} />
        <Route path='/rboasnovas' component={Rboasnovas} />
        <Route path='/re1sident' component={Re1sident} />
        <Route path='/recordnews' component={Recordnews} />
        <Route path='/recordrj' component={Recordrj} />
        <Route path='/recordsc' component={Recordsc} />
        <Route path='/redencao' component={Redencao} />
        <Route path='/redetv' component={Redetv} />
        <Route path='/rittv' component={Rittv} />
        <Route path='/romance' component={Romance} />
        <Route path='/round6' component={Round6} />
        <Route path='/ruepa' component={Ruepa} />
        <Route path='/runtimeacao' component={Runtimeacao} />
        <Route path='/runtimecom' component={Runtimecom} />
        <Route path='/runtimepri' component={Runtimepri} />
        <Route path='/ruslan' component={Ruslan} />
        <Route path='/sbt' component={Sbt} />
        <Route path='/see' component={See} />
        <Route path='/segredo' component={Segredo} />
        <Route path='/seriegot' component={Seriegot} />
        <Route path='/series' component={Series} />
        <Route path='/sosenhorda' component={Sosenhorda} />
        <Route path='/sporttv' component={Sporttv} />
        <Route path='/sporttv2' component={Sporttv2} />
        <Route path='/sporttv3' component={Sporttv3} />
        <Route path='/sporttv4' component={Sporttv4} />
        <Route path='/sulamerica' component={Sulamerica} />
        <Route path='/supermel' component={Supermel} />
        <Route path='/suspense' component={Suspense} />
        <Route path='/terror' component={Terror} />
        <Route path='/terror2' component={Terror2} />
        <Route path='/teste' component={Teste} />
        <Route path='/teste2' component={Teste2} />
        <Route path='/teste3' component={Teste3} />
        <Route path='/thriller' component={Thriller} />
        <Route path='/thriller2' component={Thriller2} />
        <Route path='/Tnts1' component={Tnts1} />
        <Route path='/tntsport2' component={Tntsport2} />
        <Route path='/Tntsports5' component={Tntsport5} />
        <Route path='/Tntsports7' component={Tntsports7} />
        <Route path='/Tntsports8' component={Tntsports8} />
        <Route path='/tophits' component={Tophits} />
        <Route path='/topmixtv' component={Topmixtv} />
        <Route path='/toptv' component={Toptv} />
        <Route path='/tvab' component={Tvab} />
        <Route path='/tvamulherb' component={Tvamulherb} />
        <Route path='/tvs' component={TVs} />
        <Route path='/tvsf' component={Tvsf} />
        <Route path='/tvsp' component={TVsp} />
        <Route path='/twinpeaks' component={Twinpeaks} />
        <Route path='/umjovememapuros' component={Umjovememapuros} />
        <Route path='/ummaluconp' component={Ummaluconp} />
        <Route path='/valedes' component={Valedes} />
        <Route path='/vdeoclips' component={Videoclips} />
        <Route path='/vikingsv' component={Vikingsv} />
        <Route path='/wandinha' component={Wandinha} />
        <Route path='/warnertv' component={Warnertv} />
        <Route path='/youtubeml' component={Youtubeml} />
       


        
        

        

       

       


        
       
  

     
 
   
        


 



        
        
   

        




        


        
      </Switch>

    </Router>
    
  );
}

export default App;
